from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


def test_health_returns_ok():
    response = client.get("/health")

    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_assess_good_payload_returns_full_score():
    payload = {
        "identifier": "urn:wise:cross-border-payments:v1",
        "dataset_name": "Cross-Border Payments Analytics Dataset",
        "description": "Aggregated dataset of international money transfer events used for fraud monitoring and corridor analysis.",
        "owner_team": "Payments Risk Engineering",
        "data_domain": "cross_border_payments",
        "access_rights": "restricted",
        "access_request_contact": "data-governance@company.com",
        "license_or_usage_terms": "Internal use only for approved analytics and risk investigations.",
        "provenance": "Derived from payment events generated by the transfer orchestration platform.",
        "schema_version": "1.0.0",
        "domain_standard": "internal-payments-metadata-v1",
        "contains_pii": True,
        "retention_policy": "Retain for 5 years, then review for deletion.",
    }

    response = client.post("/assess", json=payload)

    assert response.status_code == 200
    body = response.json()
    assert body["score"] == 1.0
    assert body["passed_checks"] == body["total_checks"]
    assert len(body["recommendations"]) == 0

    principle_scores = {item["principle"]: item["score"] for item in body["principle_scores"]}
    assert principle_scores["F"] == 1.0
    assert principle_scores["A"] == 1.0
    assert principle_scores["I"] == 1.0
    assert principle_scores["R"] == 1.0


def test_assess_incomplete_payload_returns_low_score():
    payload = {
        "identifier": "",
        "dataset_name": "Fraud Dataset",
        "description": "",
        "owner_team": "Fraud Ops",
        "data_domain": "fraud_detection",
        "access_rights": "restricted",
        "access_request_contact": None,
        "license_or_usage_terms": "",
        "provenance": "",
        "schema_version": "",
        "domain_standard": None,
        "contains_pii": True,
        "retention_policy": "",
    }

    response = client.post("/assess", json=payload)

    assert response.status_code == 200
    body = response.json()
    assert body["score"] == 0.2
    assert body["passed_checks"] == 2
    assert body["total_checks"] == 10

    failed_checks = {item["check_name"] for item in body["results"] if not item["passed"]}
    assert "identifier_present" in failed_checks
    assert "provenance_present" in failed_checks
    assert "license_or_usage_terms_present" in failed_checks

    principle_scores = {item["principle"]: item["score"] for item in body["principle_scores"]}
    assert principle_scores["A"] == 0.5
    assert principle_scores["F"] == 0.33
    assert principle_scores["I"] == 0.0
    assert principle_scores["R"] == 0.0